# `mkEngine` is accepted and ignored: engines/default.nix and test-engine.nix
# pass it to every engine file unconditionally, but Rust engines use
# rustPlatform.buildRustPackage instead.
{ lib, stdenv, buildPackages, rustPlatform, fetchFromGitHub
, mkEngine ? null }:

# Akimbo is a sub-1000-LOC minimalist Rust engine, so mkEngine does not apply;
# this is a standalone rustPlatform.buildRustPackage. The meta fields and the
# UCI smoke test below mirror lib/mkEngine.nix so the engine is held to the same
# standard as the rest of the collection.

let
  # Akimbo .gitignores its Cargo.lock, so buildRustPackage has nothing to vendor
  # from. This lock was generated with a nixpkgs cargo against the v1.0.0
  # manifest and is embedded verbatim; importCargoLock fetches each crate by the
  # checksum recorded here, so the vendored set is fully pinned and no cargoHash
  # is needed. The only dependency is bulletformat (an optional dep, gated behind
  # the `datagen` feature, but still recorded in the lock); the default engine
  # build pulls in none of it.
  lockFile = builtins.toFile "akimbo-Cargo.lock" ''
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "akimbo"
version = "1.0.0"
dependencies = [
 "bulletformat",
]

[[package]]
name = "bulletformat"
version = "0.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbf4e004fa21eb4a25d1b815e73557e1070bbe26e00ed23b828e47d9036abcb9"
  '';
in
rustPlatform.buildRustPackage rec {
  pname = "akimbo";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "jw1912";
    repo = "akimbo";
    rev = "v${version}";
    hash = "sha256-zpN5KlAyOWS8KVSRTMVdp05QsfFOeMCLCu4g2BGGy6A=";
  };

  cargoLock.lockFile = lockFile;

  # The repo .gitignores Cargo.lock, so drop the pinned one into the tree before
  # buildRustPackage's consistency check (which diffs src/Cargo.lock against the
  # vendored copy) runs.
  postPatch = ''
    cp ${lockFile} Cargo.lock
  '';

  # src/network.rs embeds the net with
  #   include_bytes!(concat!("../", env!("EVALFILE")))
  # so EVALFILE is *mandatory* at compile time (there is no default; upstream
  # sets it through a .cargo/config that is itself .gitignored). The net
  # (resources/net.bin) is a plain file committed in-tree, so we just point
  # EVALFILE at its repo-relative path; include_bytes! resolves "../" against
  # src/, giving resources/net.bin. Nothing is fetched over the network.
  EVALFILE = "resources/net.bin";

  # PGO/native codegen live only in the Makefile (cargo rustc with
  # -C target-cpu=native); buildRustPackage runs a plain `cargo build --release`
  # and never touches it. The NNUE inference has an AVX2 path
  # (#[cfg(target_feature = "avx2")]) and a scalar fallback
  # (#[cfg(not(target_feature = "avx2"))]); on aarch64 the fallback is selected,
  # so the engine builds and plays at full strength without any x86 intrinsics.

  doInstallCheck = stdenv.hostPlatform.emulatorAvailable buildPackages;

  # Same guarantee as mkEngine, plus an actual search: handshake to uciok, then
  # require a bestmove from `go depth 10`. A missing/incompatible net passes
  # the handshake but dies on `go`, so this catches net breakage too.
  installCheckPhase = ''
    runHook preInstallCheck
    emu="${stdenv.hostPlatform.emulator buildPackages}"
    bin="$out/bin/${pname}${stdenv.hostPlatform.extensions.executable}"

    out_txt=$(printf 'uci\nquit\n' | $emu "$bin" | tr -d '\r')
    echo "$out_txt" | grep -q uciok || {
      echo "FAIL: ${pname} did not answer 'uciok' to a uci handshake" >&2
      echo "$out_txt" >&2
      exit 1
    }
    echo "ok: ${pname} speaks UCI"

    search_txt=$( { printf 'uci\nisready\nposition startpos\ngo depth 10\n'; \
      sleep 4; printf 'quit\n'; } | $emu "$bin" | tr -d '\r')
    echo "$search_txt" | grep -q '^bestmove ' || {
      echo "FAIL: ${pname} returned no bestmove from 'go depth 10'" >&2
      echo "$search_txt" >&2
      exit 1
    }
    echo "ok: ${pname} searches and returns a bestmove"
    runHook postInstallCheck
  '';

  meta = with lib; {
    description = "akimbo, a minimalist NNUE UCI chess engine written in Rust";
    homepage = "https://github.com/jw1912/akimbo";
    # LICENSE in the repository root is the verbatim MIT license (c) 2023 Jamie
    # Whiting.
    license = licenses.mit;
    mainProgram = "akimbo";
    platforms = platforms.unix ++ platforms.windows;
    maintainers = [ ];
  };
}
