# `mkEngine` is accepted and ignored: engines/default.nix and test-engine.nix
# pass it to every engine file unconditionally, but C#/.NET engines use
# buildDotnetModule instead.
{ lib, stdenv, buildPackages, buildDotnetModule, dotnetCorePackages
, fetchFromGitHub, mkEngine ? null }:

# Leorik is a C# engine, so mkEngine (stdenv.mkDerivation + Makefile fixups)
# does not apply; this is a standalone buildDotnetModule. It is published
# self-contained + single-file for osx-arm64, so the result is a native
# standalone binary with NO .NET runtime required at run time. The meta fields
# and the UCI smoke test below mirror lib/mkEngine.nix so the engine is held to
# the same standard as the rest of the collection.

buildDotnetModule rec {
  pname = "leorik";
  version = "3.2";

  src = fetchFromGitHub {
    owner = "lithander";
    repo = "Leorik";
    rev = version;
    hash = "sha256-m8tAcUtvM6v3uRmMJdTXB6V/AbU6SWoVTN26HKDfuRw=";
  };

  # Leorik.Engine is the UCI front-end; the other projects are the core/search
  # libraries plus a tuner, perft and a test harness we do not want.
  projectFile = "Leorik.Engine/Leorik.Engine.csproj";

  # NuGet lockfile, generated by `passthru.fetch-deps` (see below). Leorik has
  # no third-party PackageReferences, so this only pins the self-contained
  # runtime/host/ILLink packs the osx-arm64 publish pulls in.
  nugetDeps = ./leorik-deps.json;

  # net10.0 across all Leorik projects (see the csproj files). 10.0.302 is the
  # SDK in this nixpkgs; the runtime it ships publishes the osx-arm64 apphost.
  dotnet-sdk = dotnetCorePackages.sdk_10_0;
  dotnet-runtime = dotnetCorePackages.runtime_10_0;

  # No .NET at run time: bundle the runtime into the app itself.
  selfContainedBuild = true;

  # Pin the publish to Apple silicon; the single-file apphost is RID-specific.
  runtimeId = "osx-arm64";

  # PublishSingleFile folds the managed assemblies + runtime into one apphost.
  # InvariantGlobalization drops the ICU dependency (dyld ignores the wrapper's
  # LD_LIBRARY_PATH on Darwin, so an ICU-linked build would fail to start); the
  # engine only ever parses ASCII UCI, so invariant culture is harmless.
  dotnetInstallFlags = [
    "-p:PublishSingleFile=true"
    "-p:InvariantGlobalization=true"
  ];

  # Wrap and expose the apphost. The NNUE net (640HL-S-5io8-6116M-FRCv1.nnue,
  # committed in Leorik.Core) is copied next to the binary at publish time and
  # loaded at run time by globbing AppDomain.BaseDirectory - so it stays a
  # sidecar in $out/lib/leorik and must not be bundled into the single file.
  executables = [ "Leorik.Engine" ];

  # Give the wrapped binary the collection's conventional name.
  postFixup = ''
    ln -s Leorik.Engine "$out/bin/leorik"
  '';

  doInstallCheck = stdenv.hostPlatform.emulatorAvailable buildPackages;

  # Same guarantee as mkEngine, plus an actual search: handshake to uciok, then
  # require a bestmove from `go depth 8`. A missing/unreadable net passes the
  # handshake but produces no move, so this catches net breakage too. The sleep
  # gives the search real wall-clock time before `quit`.
  installCheckPhase = ''
    runHook preInstallCheck
    emu="${stdenv.hostPlatform.emulator buildPackages}"
    bin="$out/bin/leorik${stdenv.hostPlatform.extensions.executable}"

    out_txt=$(printf 'uci\nquit\n' | $emu "$bin" | tr -d '\r')
    echo "$out_txt" | grep -q uciok || {
      echo "FAIL: ${pname} did not answer 'uciok' to a uci handshake" >&2
      echo "$out_txt" >&2
      exit 1
    }
    echo "ok: ${pname} speaks UCI"

    search_txt=$( { printf 'uci\nisready\nposition startpos\ngo depth 8\n'; \
      sleep 4; printf 'quit\n'; } | $emu "$bin" | tr -d '\r')
    echo "$search_txt" | grep -q '^bestmove ' || {
      echo "FAIL: ${pname} returned no bestmove from 'go depth 8'" >&2
      echo "$search_txt" >&2
      exit 1
    }
    echo "ok: ${pname} searches and returns a bestmove"
    runHook postInstallCheck
  '';

  meta = with lib; {
    description = "Leorik, a C# NNUE UCI engine by Thomas Jahn";
    homepage = "https://github.com/lithander/Leorik";
    # LICENSE in the repository root is the verbatim MIT licence text.
    license = licenses.mit;
    mainProgram = "leorik";
    # Published self-contained single-file for the osx-arm64 RID only.
    platforms = [ "aarch64-darwin" ];
    maintainers = [ ];
  };
}
