# `mkEngine` is accepted and ignored: engines/default.nix and test-engine.nix
# pass it to every engine file unconditionally, but C#/.NET engines use
# buildDotnetModule instead.
{ lib, stdenv, buildPackages, buildDotnetModule, dotnetCorePackages
, fetchFromGitHub, mkEngine ? null }:

# Lynx is a C# engine (HCE, no NNUE net), so mkEngine does not apply; this is a
# standalone buildDotnetModule. It is published self-contained + single-file for
# osx-arm64, so the result is a native standalone binary with NO .NET runtime
# required at run time. The meta fields and the UCI smoke test below mirror
# lib/mkEngine.nix so the engine is held to the same standard as the rest of the
# collection.

buildDotnetModule rec {
  pname = "lynx";
  version = "1.11.0";

  src = fetchFromGitHub {
    owner = "lynx-chess";
    repo = "Lynx";
    rev = "v${version}";
    hash = "sha256-t2cs0X5GJsNRP6c3IKzmDFRpcOZ6Jbhm2eAKiYzuaXU=";
  };

  # Lynx.Cli is the UCI front-end; Lynx is the core library it references. The
  # Benchmark/Dev/ConstantsGenerator projects are development-only.
  projectFile = "src/Lynx.Cli/Lynx.Cli.csproj";

  # NuGet lockfile, generated by `passthru.fetch-deps` (see below). Lynx pulls
  # NLog, Macross.Json.Extensions, several Microsoft.Extensions.* packages and a
  # set of build-time analyzers, plus the self-contained osx-arm64 runtime/host/
  # ILLink packs; all are pinned here.
  nugetDeps = ./lynx-deps.json;

  # v1.11.0 targets net9.0 (Directory.Build.props) and global.json pins the SDK
  # to 9.0.x with rollForward=latestMinor, so build with the 9.0 SDK, not 10.0.
  dotnet-sdk = dotnetCorePackages.sdk_9_0;
  dotnet-runtime = dotnetCorePackages.runtime_9_0;

  # No .NET at run time: bundle the runtime into the app itself.
  selfContainedBuild = true;

  # Pin the publish to Apple silicon; the single-file apphost is RID-specific.
  # Lynx guards its BMI2/x86 intrinsics behind runtime IsSupported checks, so
  # the arm64 codegen simply takes the portable path - no x86 build flags leak
  # in, and PublishReadyToRun is off (Optimized) so all codegen is arm64.
  runtimeId = "osx-arm64";

  # `-p:Optimized=true` is Lynx's own release switch (see Lynx.Cli.csproj and the
  # upstream Makefile): it turns on SelfContained, PublishSingleFile,
  # PublishTrimmed, IncludeNativeLibrariesForSelfExtract and disables ReadyToRun
  # in favour of tiered JIT. Passed in all phases so restore/build/publish agree.
  # InvariantGlobalization is already set repo-wide in Directory.Build.props.
  dotnetFlags = [ "-p:Optimized=true" ];

  # Rename the published apphost (default AssemblyName Lynx.Cli) to `lynx`, via
  # the csproj's own post-publish Rename target.
  dotnetInstallFlags = [ "-p:ExecutableName=lynx" ];
  executables = [ "lynx" ];

  doInstallCheck = stdenv.hostPlatform.emulatorAvailable buildPackages;

  # Same guarantee as mkEngine, plus an actual search: handshake to uciok, then
  # require a bestmove from `go depth 8`. The sleep gives the search real
  # wall-clock time before `quit` rather than a burst that races startup.
  installCheckPhase = ''
    runHook preInstallCheck
    emu="${stdenv.hostPlatform.emulator buildPackages}"
    bin="$out/bin/lynx${stdenv.hostPlatform.extensions.executable}"

    out_txt=$(printf 'uci\nquit\n' | $emu "$bin" | tr -d '\r')
    echo "$out_txt" | grep -q uciok || {
      echo "FAIL: ${pname} did not answer 'uciok' to a uci handshake" >&2
      echo "$out_txt" >&2
      exit 1
    }
    echo "ok: ${pname} speaks UCI"

    search_txt=$( { printf 'uci\nisready\nposition startpos\ngo depth 8\n'; \
      sleep 4; printf 'quit\n'; } | $emu "$bin" | tr -d '\r')
    echo "$search_txt" | grep -q '^bestmove ' || {
      echo "FAIL: ${pname} returned no bestmove from 'go depth 8'" >&2
      echo "$search_txt" >&2
      exit 1
    }
    echo "ok: ${pname} searches and returns a bestmove"
    runHook postInstallCheck
  '';

  meta = with lib; {
    description = "Lynx, a C# HCE UCI chess engine by Eduardo Cáceres";
    homepage = "https://github.com/lynx-chess/Lynx";
    # LICENSE in the repository root is the verbatim MIT licence text.
    license = licenses.mit;
    mainProgram = "lynx";
    # Published self-contained single-file for the osx-arm64 RID only.
    platforms = [ "aarch64-darwin" ];
    maintainers = [ ];
  };
}
